---
- name: Install PostgreSQL 13
  hosts: psqlsv
  become: yes
  roles:
  - postgres

- name: Install Odoo 15
  hosts: odoosv
  become: yes
  roles:
  - odoo15

- name: Install NGINX
  hosts: nginxsv
  become: yes
  roles:
  - nginx
