---
- name: Install Odoo 15
  hosts: odoosv
  become: yes
  pre_tasks:
  - name: set variables
    set_fact:    
      odoo_user: 'odoo'
      db_user: 'odoo'
      odoo_port: '8069'
      psql_port: '5432'
  
  tasks:
  - name: Update package cache
    package:
      update_cache: yes
  - name: Update server
    apt:
      upgrade: safe
      state: latest
  - name: Installing python3 and pip3
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - python3
    - python3-pip
    - python3-dev
    - libxml2-dev
    - libpq-dev
    - liblcms2-dev
    - libxslt1-dev
    - zlib1g-dev
    - libsasl2-dev
    - libldap2-dev
    - build-essential
    - git
    - libssl-dev
    - libffi-dev
    - libjpeg-dev
    - libblas-dev

  - name: Install nodejs npm
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - nodejs
    - npm
    - node-less
  - name: Install npm packages
    npm:
      name: "{{ item }}"
      path: /vagrant_data/package-lock.json
      state: present
    with_items:
    - less
    - less-plugin-clean-css
