---
# handlers file for odoo15

- name: restart odoo
  service:
    name: "{{ odoo_daemon }}"
    state: restarted
  when: not odoo_role_dev_mode | bool

- name: Reload systemd
  systemd:
    daemon-reload: yes
  when: ansible_service_mgr == 'systemd'
