---
- name: Add postgres repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Configure apt repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main"
    state: present
    update_cache: yes

- name: Install package postgresql-common
  apt:
    name: postgresql-common
    state: present
    
- name: Install package postgresql-13
  apt:
    name: postgresql-13
    state: present
    
- name: Install package libpq-dev
  apt:
    name: libpq-dev
    state: present
    
- name: Install package python3-psycopg2
  apt:
    name: python3-psycopg2
    state: latest
    
- name: Start postgresql
  service:
    name: postgresql
    state: started
    
- name: Create database
  postgresql_db:
    name: "{{ db_user }}"
    state: present
  become: yes
  become_user: postgres
    
- name: Create user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
    role_attr_flags: "SUPERUSER"
  become: yes
  become_user: postgres
    
- name: Configure authentication for Odoo
  postgresql_pg_hba:
    dest: /etc/postgresql/13/main/pg_hba.conf
    contype: host
    databases: all
    method: md5
    create: true
    users: "{{ db_user }}"
    source: 192.168.56.11/24
  become: yes
  become_user: postgres
  notify: Reload Postgres
